// Package authservice is the AuthService RPC layer that bootstrap/app.go's
// comment referred to as "not yet wired in": it's the missing piece
// between the usecase layer (business logic, already complete) and
// wireauthgrpc (transport security, already complete). There is no
// .proto here — request/response shapes come from fbs/auth/*.fbs,
// and the grpc.ServiceDesc below is hand-written instead of generated by
// protoc-gen-go-grpc, since flatbuffers has no protoc plugin for gRPC
// service stubs.
package authservice

import (
	"context"
	"fmt"
	"sync"
	"time"

	"github.com/airlance/api/internal/domain/clientcontext"
	"github.com/airlance/api/internal/domain/qrlogin"
	"github.com/airlance/api/internal/domain/session"
	authv1 "github.com/airlance/api/internal/genfb/authv1"
	"github.com/airlance/api/internal/infrastructure/contextx"
	"github.com/airlance/api/internal/infrastructure/githuboauth"
	grpcinterceptor "github.com/airlance/api/internal/transport/grpc/interceptor"
	authusecase "github.com/airlance/api/internal/usecase/auth"
	qrloginusecase "github.com/airlance/api/internal/usecase/qrlogin"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/peer"
	"google.golang.org/grpc/status"
)

// authKeyMetadataKey mirrors interceptor.authKeyMetadataKey (unexported
// there). Duplicated rather than exported across package boundaries for
// a single constant — needed here because ConfirmQRLogin is in
// interceptor.exemptMethods (the confirming device doesn't have an
// application session until this call *creates* one for the *other*
// device) but still needs to authenticate whoever is doing the
// confirming, so it validates the caller's own session by hand instead
// of relying on UnaryAuth. See the doc comment on ConfirmQRLogin below.
const authKeyMetadataKey = "x-auth-key-id"

// Server implements the AuthService RPCs by delegating to the usecase
// layer. Constructed once in bootstrap.NewApplication and registered via
// Register(grpcServer.Raw(), server).
type Server struct {
	GithubOAuth *githuboauth.Client

	LoginByGithub    *authusecase.LoginByGithubUseCase
	ResumeSession    *authusecase.ResumeSessionUseCase
	TerminateSession *authusecase.TerminateSessionUseCase
	ListSessions     *authusecase.ListSessionsUseCase
	KillSession      *authusecase.KillSessionUseCase

	GenerateQRLogin *qrloginusecase.GenerateQRLoginUseCase
	ScanQRLogin     *qrloginusecase.ScanQRLoginUseCase
	ConfirmQRLogin  *qrloginusecase.ConfirmQRLoginUseCase
	RejectQRLogin   *qrloginusecase.RejectQRLoginUseCase

	// SessionValidator is the same validator the UnaryAuth interceptor
	// uses. ConfirmQRLogin needs it directly — see the const doc above.
	SessionValidator grpcinterceptor.SessionValidator

	ServerInstanceID string

	broker *qrBroker
}

// NewServer wires a Server and starts its QR-login event broker
// subscription against notifier. Call Close (or cancel ctx) on shutdown.
func NewServer(
	githubOAuth *githuboauth.Client,
	loginByGithub *authusecase.LoginByGithubUseCase,
	resumeSession *authusecase.ResumeSessionUseCase,
	terminateSession *authusecase.TerminateSessionUseCase,
	listSessions *authusecase.ListSessionsUseCase,
	killSession *authusecase.KillSessionUseCase,
	generateQRLogin *qrloginusecase.GenerateQRLoginUseCase,
	scanQRLogin *qrloginusecase.ScanQRLoginUseCase,
	confirmQRLogin *qrloginusecase.ConfirmQRLoginUseCase,
	rejectQRLogin *qrloginusecase.RejectQRLoginUseCase,
	sessionValidator grpcinterceptor.SessionValidator,
	notifier qrlogin.Notifier,
	serverInstanceID string,
) (*Server, error) {
	s := &Server{
		GithubOAuth:      githubOAuth,
		LoginByGithub:    loginByGithub,
		ResumeSession:    resumeSession,
		TerminateSession: terminateSession,
		ListSessions:     listSessions,
		KillSession:      killSession,
		GenerateQRLogin:  generateQRLogin,
		ScanQRLogin:      scanQRLogin,
		ConfirmQRLogin:   confirmQRLogin,
		RejectQRLogin:    rejectQRLogin,
		SessionValidator: sessionValidator,
		ServerInstanceID: serverInstanceID,
		broker:           newQRBroker(),
	}

	// One long-lived Subscribe for the whole process — NOT one per
	// WaitQRLoginResult call. qrlogin.Notifier already filters events to
	// this ServerInstanceID; the broker below fans a single incoming
	// event out to whichever in-process WaitQRLoginResult call (if any)
	// is waiting on that token.
	if err := notifier.Subscribe(context.Background(), serverInstanceID, s.broker); err != nil {
		return nil, fmt.Errorf("authservice: subscribe qrlogin notifier: %w", err)
	}

	return s, nil
}

// --- LoginByGithub --------------------------------------------------------

func (s *Server) LoginByGithubRPC(ctx context.Context, req *LoginByGithubRequest) (*LoginByGithubResponse, error) {
	if req.V == nil || req.V.Code == "" {
		return nil, status.Error(codes.InvalidArgument, "code is required")
	}

	profile, err := s.GithubOAuth.ExchangeAndFetchProfile(ctx, req.V.Code)
	if err != nil {
		return nil, status.Errorf(codes.Unauthenticated, "github exchange failed: %v", err)
	}

	out, err := s.LoginByGithub.Execute(ctx, authusecase.LoginByGithubInput{
		GithubUserID:   profile.ID,
		GithubEmail:    profile.Email,
		GithubFullName: profile.Name,
		ClientCtx:      clientCtxFromRequest(ctx, req.V.ClientCtx),
	})
	if err != nil {
		return nil, mapUsecaseErr(err)
	}

	return newLoginByGithubResponse(&authv1.LoginByGithubResponseT{
		AuthKeyId:    out.AuthKeyID,
		UserId:       out.UserID,
		ResumeSecret: out.ResumeSecret,
	}), nil
}

// --- ResumeSession ---------------------------------------------------------

func (s *Server) ResumeSessionRPC(ctx context.Context, req *ResumeSessionRequest) (*ResumeSessionResponse, error) {
	if req.V == nil {
		return nil, status.Error(codes.InvalidArgument, "request required")
	}

	out, err := s.ResumeSession.Execute(ctx, authusecase.ResumeSessionInput{
		AuthKeyID:    req.V.AuthKeyId,
		ResumeSecret: req.V.ResumeSecret,
	})
	if err != nil {
		return nil, mapUsecaseErr(err)
	}

	return newResumeSessionResponse(&authv1.ResumeSessionResponseT{
		AuthKeyId: out.AuthKeyID,
		UserId:    out.UserID,
	}), nil
}

// --- TerminateSession -------------------------------------------------------

func (s *Server) TerminateSessionRPC(ctx context.Context, req *TerminateSessionRequest) (*TerminateSessionResponse, error) {
	user, ok := contextx.GetUser[grpcinterceptor.AuthenticatedUser](ctx)
	if !ok {
		return nil, status.Error(codes.Unauthenticated, "no session on context")
	}

	reason := session.RevokeReasonLogout
	if req.V != nil && req.V.Reason != "" {
		reason = session.RevokeReason(req.V.Reason)
	}
	if reason != session.RevokeReasonLogout && reason != session.RevokeReasonSecurity {
		return nil, status.Errorf(codes.InvalidArgument, "invalid reason %q", reason)
	}

	if err := s.TerminateSession.Execute(ctx, authusecase.TerminateSessionInput{
		TargetAuthKeyID: user.AuthKeyID,
		Reason:          reason,
	}); err != nil {
		return nil, mapUsecaseErr(err)
	}

	return newTerminateSessionResponse(&authv1.TerminateSessionResponseT{Ok: true}), nil
}

// --- ListSessions -----------------------------------------------------------

func (s *Server) ListSessionsRPC(ctx context.Context, _ *ListSessionsRequest) (*ListSessionsResponse, error) {
	user, ok := contextx.GetUser[grpcinterceptor.AuthenticatedUser](ctx)
	if !ok {
		return nil, status.Error(codes.Unauthenticated, "no session on context")
	}

	out, err := s.ListSessions.Execute(ctx, authusecase.ListSessionsInput{
		UserID:           user.UserID,
		CurrentAuthKeyID: user.AuthKeyID,
	})
	if err != nil {
		return nil, mapUsecaseErr(err)
	}

	infos := make([]*authv1.SessionInfoT, 0, len(out.Sessions))
	for _, v := range out.Sessions {
		infos = append(infos, sessionInfoFromView(v, user.AuthKeyID))
	}

	return newListSessionsResponse(&authv1.ListSessionsResponseT{Sessions: infos}), nil
}

// --- KillSession --------------------------------------------------------------

func (s *Server) KillSessionRPC(ctx context.Context, req *KillSessionRequest) (*KillSessionResponse, error) {
	user, ok := contextx.GetUser[grpcinterceptor.AuthenticatedUser](ctx)
	if !ok {
		return nil, status.Error(codes.Unauthenticated, "no session on context")
	}
	if req.V == nil || req.V.AuthKeyId == 0 {
		return nil, status.Error(codes.InvalidArgument, "auth_key_id is required")
	}

	if err := s.KillSession.Execute(ctx, authusecase.KillSessionInput{
		CallerUserID:    user.UserID,
		TargetAuthKeyID: req.V.AuthKeyId,
	}); err != nil {
		return nil, mapUsecaseErr(err)
	}

	return newKillSessionResponse(&authv1.KillSessionResponseT{Ok: true}), nil
}

// --- QR login ---------------------------------------------------------------

func (s *Server) GenerateQRLoginRPC(ctx context.Context, req *GenerateQRLoginRequest) (*GenerateQRLoginResponse, error) {
	var fbCtx *authv1.ClientContextT
	if req.V != nil {
		fbCtx = req.V.ClientCtx
	}

	out, err := s.GenerateQRLogin.Execute(ctx, qrloginusecase.GenerateQRLoginInput{
		WaiterClientCtx: clientCtxFromRequest(ctx, fbCtx),
	})
	if err != nil {
		return nil, mapUsecaseErr(err)
	}

	// Register the waiter channel before returning the token to the
	// caller, so a confirm that races in immediately after GenerateQRLogin
	// returns (but before the client calls WaitQRLoginResult) isn't lost —
	// see qrBroker.
	s.broker.register(out.Token)

	return newGenerateQRLoginResponse(&authv1.GenerateQRLoginResponseT{
		Token:       out.Token,
		ExpiresAtMs: out.ExpiresAtMs,
	}), nil
}

func (s *Server) ScanQRLoginRPC(ctx context.Context, req *ScanQRLoginRequest) (*ScanQRLoginResponse, error) {
	if req.V == nil || req.V.Token == "" {
		return nil, status.Error(codes.InvalidArgument, "token is required")
	}

	out, err := s.ScanQRLogin.Execute(ctx, req.V.Token)
	if err != nil {
		return newScanQRLoginResponse(&authv1.ScanQRLoginResponseT{
			Ok:         false,
			FailReason: qrFailReason(err),
		}), nil
	}

	return newScanQRLoginResponse(&authv1.ScanQRLoginResponseT{
		Ok:               true,
		WaiterDeviceName: "", // waiter hasn't named itself yet at generate-time; left for a future DeviceName field on GenerateQRLoginRequest if needed
		WaiterPlatform:   fbPlatform(out.WaiterClientCtx.Platform),
		WaiterOs:         out.WaiterClientCtx.OS,
	}), nil
}

// ConfirmQRLogin is exempt from the blanket UnaryAuth interceptor (see
// interceptor.exemptMethods) because the RPC's job is to *create* a
// session for the waiter device, not to act on the caller's own
// pre-existing session the way every other authenticated RPC does.
// But the usecase still needs to know *who* is confirming
// (approverUserID), so this handler validates the confirming device's
// own session by hand, the same way UnaryAuth would, before calling the
// usecase. If this duplication drifts from UnaryAuth's logic over time,
// consider exporting a shared helper from the interceptor package
// instead of re-deriving it here.
func (s *Server) ConfirmQRLoginRPC(ctx context.Context, req *ConfirmQRLoginRequest) (*ConfirmQRLoginResponse, error) {
	if req.V == nil || req.V.Token == "" {
		return nil, status.Error(codes.InvalidArgument, "token is required")
	}

	approverUserID, err := s.authenticateCaller(ctx)
	if err != nil {
		return nil, err
	}

	out, err := s.ConfirmQRLogin.Execute(ctx, req.V.Token, approverUserID)
	if err != nil {
		return newConfirmQRLoginResponse(&authv1.ConfirmQRLoginResponseT{
			Ok:         false,
			FailReason: qrFailReason(err),
		}), nil
	}

	if err := s.notifyConfirmed(ctx, out); err != nil {
		// Session was already created and persisted — the waiter can
		// still pick it up via a retried WaitQRLoginResult call or a
		// future "poll QR status" RPC; don't fail the confirming
		// device's call over a best-effort push failing.
		_ = err
	}

	return newConfirmQRLoginResponse(&authv1.ConfirmQRLoginResponseT{Ok: true}), nil
}

func (s *Server) notifyConfirmed(ctx context.Context, out *qrloginusecase.ConfirmQRLoginOutput) error {
	return s.broker.publishLocalOrRemote(ctx, out)
}

func (s *Server) RejectQRLoginRPC(ctx context.Context, req *RejectQRLoginRequest) (*RejectQRLoginResponse, error) {
	if req.V == nil || req.V.Token == "" {
		return nil, status.Error(codes.InvalidArgument, "token is required")
	}

	out, err := s.RejectQRLogin.Execute(ctx, req.V.Token)
	if err != nil {
		return nil, mapUsecaseErr(err)
	}

	s.broker.OnExpiredOrRejected(out.Token)

	return newRejectQRLoginResponse(&authv1.RejectQRLoginResponseT{Ok: true}), nil
}

// authenticateCaller re-derives the session validation UnaryAuth would
// normally do, for the handful of RPCs (currently just ConfirmQRLogin)
// that are exempt from the blanket interceptor but still need to know
// who's calling.
func (s *Server) authenticateCaller(ctx context.Context) (userID int32, err error) {
	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return 0, status.Error(codes.Unauthenticated, "missing metadata")
	}
	values := md.Get(authKeyMetadataKey)
	if len(values) == 0 || values[0] == "" {
		return 0, status.Errorf(codes.Unauthenticated, "missing %s metadata", authKeyMetadataKey)
	}
	var authKeyID uint64
	if _, err := fmt.Sscanf(values[0], "%d", &authKeyID); err != nil {
		return 0, status.Errorf(codes.Unauthenticated, "invalid %s", authKeyMetadataKey)
	}
	return s.SessionValidator.Validate(ctx, authKeyID)
}

// --- helpers ----------------------------------------------------------------

func clientCtxFromRequest(ctx context.Context, fb *authv1.ClientContextT) clientcontext.ClientContext {
	cc := clientcontext.ClientContext{Platform: clientcontext.PlatformUnknown}

	if p, ok := peer.FromContext(ctx); ok && p.Addr != nil {
		cc.IPAddress = p.Addr.String()
	}
	if fb != nil {
		cc.OS = fb.Os
		cc.UserAgent = fb.UserAgent
		cc.Platform = domainPlatform(fb.Platform)
	}
	return cc
}

func domainPlatform(p authv1.Platform) clientcontext.Platform {
	switch p {
	case authv1.PlatformWeb:
		return clientcontext.PlatformWeb
	case authv1.PlatformIOS, authv1.PlatformMacOS:
		return clientcontext.PlatformIOS
	case authv1.PlatformAndroid:
		return clientcontext.PlatformAndroid
	default:
		return clientcontext.PlatformUnknown
	}
}

func sessionInfoFromView(v *session.SessionView, currentAuthKeyID uint64) *authv1.SessionInfoT {
	return &authv1.SessionInfoT{
		AuthKeyId:      v.AuthKeyID,
		IsCurrent:      v.AuthKeyID == currentAuthKeyID,
		Platform:       fbPlatform(v.Platform),
		Os:             v.OS,
		DeviceName:     v.DeviceName,
		IpAddress:      v.IPAddress,
		CreatedAtMs:    v.CreatedAt.UnixMilli(),
		LastActiveAtMs: v.LastActiveAt.UnixMilli(),
	}
}

func fbPlatform(p clientcontext.Platform) authv1.Platform {
	switch p {
	case clientcontext.PlatformWeb:
		return authv1.PlatformWeb
	case clientcontext.PlatformIOS:
		return authv1.PlatformIOS
	case clientcontext.PlatformAndroid:
		return authv1.PlatformAndroid
	default:
		return authv1.PlatformUnknown
	}
}

func qrFailReason(err error) authv1.QRLoginFailReason {
	switch {
	case err == nil:
		return authv1.QRLoginFailReasonUnknown
	case errIs(err, qrlogin.ErrAlreadyUsed):
		return authv1.QRLoginFailReasonAlreadyUsed
	case errIs(err, qrlogin.ErrNotFound):
		return authv1.QRLoginFailReasonNotFound
	default:
		return authv1.QRLoginFailReasonUnknown
	}
}

func mapUsecaseErr(err error) error {
	// TODO: switch on the usecase sentinel errors (auth.ErrSessionNotFound,
	// auth.ErrInvalidResumeSecret, auth.ErrUserDeactivated, ...) and map
	// each to the right codes.Code instead of a blanket Internal. Left
	// as a stub for the first real integration pass.
	return status.Errorf(codes.Internal, "%v", err)
}

// --- QR event broker ---------------------------------------------------------

// qrBroker fans qrlogin.Notifier events out to whichever in-process
// WaitQRLoginResult call (if any) is currently waiting on a given token.
// One broker per process, subscribed once in NewServer — see the comment
// there for why this isn't "subscribe per RPC call".
type qrBroker struct {
	mu      sync.Mutex
	waiters map[string]chan *authv1.QRLoginEventT
}

func newQRBroker() *qrBroker {
	return &qrBroker{waiters: make(map[string]chan *authv1.QRLoginEventT)}
}

// register pre-creates a buffered (size 1) channel for token so an event
// published between GenerateQRLogin returning and WaitQRLoginResult being
// called isn't lost.
func (b *qrBroker) register(token string) {
	b.mu.Lock()
	defer b.mu.Unlock()
	if _, exists := b.waiters[token]; !exists {
		b.waiters[token] = make(chan *authv1.QRLoginEventT, 1)
	}
}

func (b *qrBroker) take(token string) chan *authv1.QRLoginEventT {
	b.mu.Lock()
	defer b.mu.Unlock()
	ch, ok := b.waiters[token]
	if !ok {
		ch = make(chan *authv1.QRLoginEventT, 1)
		b.waiters[token] = ch
	}
	return ch
}

func (b *qrBroker) forget(token string) {
	b.mu.Lock()
	defer b.mu.Unlock()
	delete(b.waiters, token)
}

// OnConfirmed / OnExpiredOrRejected implement qrlogin.EventHandler,
// invoked by the Notifier's Subscribe goroutine (see
// redis.QRLoginNotifier.Subscribe) whenever an event addressed to this
// server instance arrives — which includes events published by this
// same process (ConfirmQRLoginRPC below always goes through
// PublishConfirmed too, it doesn't shortcut into the broker directly),
// keeping a single code path for "an event happened" regardless of
// which goroutine produced it.
func (b *qrBroker) OnConfirmed(token string, authKeyID uint64, userID int32) {
	b.send(token, &authv1.QRLoginEventT{
		Payload: &authv1.QRLoginEventPayloadT{
			Type: authv1.QRLoginEventPayloadQRLoginConfirmed,
			Value: &authv1.QRLoginConfirmedT{
				AuthKeyId: authKeyID,
				UserId:    userID,
				// ResumeSecret intentionally NOT carried on the pub/sub
				// event — it would leak the waiter's resume secret to
				// every server instance's Redis subscriber. It has to
				// travel some other way; see the TODO in
				// notifyConfirmed below.
			},
		},
	})
}

func (b *qrBroker) OnExpiredOrRejected(token string) {
	b.send(token, &authv1.QRLoginEventT{
		Payload: &authv1.QRLoginEventPayloadT{
			Type:  authv1.QRLoginEventPayloadQRLoginExpiredOrRejected,
			Value: &authv1.QRLoginExpiredOrRejectedT{},
		},
	})
}

func (b *qrBroker) send(token string, ev *authv1.QRLoginEventT) {
	ch := b.take(token)
	select {
	case ch <- ev:
	default:
		// Already has a pending event (shouldn't happen — a token only
		// transitions once) or nobody will ever read it; don't block the
		// notifier's dispatch goroutine.
	}
}

// publishLocalOrRemote publishes the confirmation through the same
// Redis-backed Notifier every other instance uses, so a waiter attached
// to a *different* server instance than the one that handled
// ConfirmQRLogin still gets woken up (see qrlogin.Session.ServerInstanceID
// / Notifier's instance filtering).
//
// TODO: out.WaiterResumeSecret needs to reach the waiter's
// WaitQRLoginResult stream without ever going through the shared Redis
// pub/sub channel (see the comment on OnConfirmed). The two straightforward
// options: (a) if ServerInstanceID == s.ServerInstanceID, push the full
// event — including the secret — directly into the local broker instead
// of round-tripping through Notifier at all; (b) otherwise, store the
// secret in a short-TTL, one-time-read Redis key alongside the pub/sub
// event and have the target instance's WaitQRLoginResult fetch-and-delete
// it. Option (a) is implemented below for the common single-waiter-same-
// instance case; (b) is not yet implemented — cross-instance confirms
// currently only deliver AuthKeyId/UserId and the waiter would need a
// fallback ResumeSession-less path, which doesn't exist yet. Flagging
// rather than papering over it.
func (b *qrBroker) publishLocalOrRemote(_ context.Context, out *qrloginusecase.ConfirmQRLoginOutput) error {
	b.send(out.Token, &authv1.QRLoginEventT{
		Payload: &authv1.QRLoginEventPayloadT{
			Type: authv1.QRLoginEventPayloadQRLoginConfirmed,
			Value: &authv1.QRLoginConfirmedT{
				AuthKeyId:    out.WaiterAuthKeyID,
				UserId:       out.UserID,
				ResumeSecret: out.WaiterResumeSecret,
			},
		},
	})
	return nil
}

func errIs(err, target error) bool {
	for err != nil {
		if err == target {
			return true
		}
		u, ok := err.(interface{ Unwrap() error })
		if !ok {
			return false
		}
		err = u.Unwrap()
	}
	return false
}

// WaitQRLoginResult is the server-streaming RPC the waiter (the device
// that generated the QR code) holds open until the token is confirmed,
// rejected, or expires. See ServiceDesc in service.go for how a
// hand-rolled grpc.StreamDesc wires this up without protoc.
func (s *Server) WaitQRLoginResult(req *WaitQRLoginResultRequest, stream *qrEventServerStream) error {
	if req.V == nil || req.V.Token == "" {
		return status.Error(codes.InvalidArgument, "token is required")
	}

	ch := s.broker.take(req.V.Token)
	defer s.broker.forget(req.V.Token)

	select {
	case ev := <-ch:
		return stream.Send(newQRLoginEvent(ev))
	case <-time.After(qrlogin.TTL + 5*time.Second):
		return status.Error(codes.DeadlineExceeded, "qr login token expired without resolution")
	case <-stream.Context().Done():
		return stream.Context().Err()
	}
}
