// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DeviceRevokeResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsDeviceRevokeResponse(buf []byte, offset flatbuffers.UOffsetT) *DeviceRevokeResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeviceRevokeResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishDeviceRevokeResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDeviceRevokeResponse(buf []byte, offset flatbuffers.UOffsetT) *DeviceRevokeResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DeviceRevokeResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDeviceRevokeResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DeviceRevokeResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeviceRevokeResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeviceRevokeResponse) DeviceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func DeviceRevokeResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DeviceRevokeResponseAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(deviceId), 0)
}
func DeviceRevokeResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
