// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DeviceRevokeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsDeviceRevokeRequest(buf []byte, offset flatbuffers.UOffsetT) *DeviceRevokeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeviceRevokeRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishDeviceRevokeRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDeviceRevokeRequest(buf []byte, offset flatbuffers.UOffsetT) *DeviceRevokeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DeviceRevokeRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDeviceRevokeRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DeviceRevokeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeviceRevokeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeviceRevokeRequest) DeviceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func DeviceRevokeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DeviceRevokeRequestAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(deviceId), 0)
}
func DeviceRevokeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
