// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DeviceListRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsDeviceListRequest(buf []byte, offset flatbuffers.UOffsetT) *DeviceListRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeviceListRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishDeviceListRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDeviceListRequest(buf []byte, offset flatbuffers.UOffsetT) *DeviceListRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DeviceListRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDeviceListRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DeviceListRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeviceListRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func DeviceListRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func DeviceListRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
