// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DeviceInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsDeviceInfo(buf []byte, offset flatbuffers.UOffsetT) *DeviceInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeviceInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishDeviceInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDeviceInfo(buf []byte, offset flatbuffers.UOffsetT) *DeviceInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DeviceInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDeviceInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DeviceInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeviceInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeviceInfo) DeviceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DeviceInfo) Platform() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DeviceInfo) CreatedAtMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DeviceInfo) MutateCreatedAtMs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *DeviceInfo) LastSeenAtMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DeviceInfo) MutateLastSeenAtMs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *DeviceInfo) LastAppVersion() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DeviceInfo) RevokedAtMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DeviceInfo) MutateRevokedAtMs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func (rcv *DeviceInfo) IsCurrent() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *DeviceInfo) MutateIsCurrent(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func DeviceInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func DeviceInfoAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(deviceId), 0)
}
func DeviceInfoAddPlatform(builder *flatbuffers.Builder, platform flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(platform), 0)
}
func DeviceInfoAddCreatedAtMs(builder *flatbuffers.Builder, createdAtMs uint64) {
	builder.PrependUint64Slot(2, createdAtMs, 0)
}
func DeviceInfoAddLastSeenAtMs(builder *flatbuffers.Builder, lastSeenAtMs uint64) {
	builder.PrependUint64Slot(3, lastSeenAtMs, 0)
}
func DeviceInfoAddLastAppVersion(builder *flatbuffers.Builder, lastAppVersion flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(lastAppVersion), 0)
}
func DeviceInfoAddRevokedAtMs(builder *flatbuffers.Builder, revokedAtMs uint64) {
	builder.PrependUint64Slot(5, revokedAtMs, 0)
}
func DeviceInfoAddIsCurrent(builder *flatbuffers.Builder, isCurrent bool) {
	builder.PrependBoolSlot(6, isCurrent, false)
}
func DeviceInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
