// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DeviceListResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsDeviceListResponse(buf []byte, offset flatbuffers.UOffsetT) *DeviceListResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeviceListResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishDeviceListResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDeviceListResponse(buf []byte, offset flatbuffers.UOffsetT) *DeviceListResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DeviceListResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDeviceListResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DeviceListResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeviceListResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeviceListResponse) Devices(obj *DeviceInfo, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DeviceListResponse) DevicesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func DeviceListResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DeviceListResponseAddDevices(builder *flatbuffers.Builder, devices flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(devices), 0)
}
func DeviceListResponseStartDevicesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DeviceListResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
