// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Envelope struct {
	_tab flatbuffers.Table
}

func GetRootAsEnvelope(buf []byte, offset flatbuffers.UOffsetT) *Envelope {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Envelope{}
	x.Init(buf, n+offset)
	return x
}

func FinishEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEnvelope(buf []byte, offset flatbuffers.UOffsetT) *Envelope {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Envelope{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEnvelopeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Envelope) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Envelope) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Envelope) ProtocolVersion() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Envelope) MutateProtocolVersion(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *Envelope) ClientVersion() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Envelope) MutateClientVersion(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *Envelope) MessageId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Envelope) MutateMessageId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *Envelope) CorrelationId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Envelope) MutateCorrelationId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *Envelope) PayloadType() Payload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return Payload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Envelope) MutatePayloadType(n Payload) bool {
	return rcv._tab.MutateByteSlot(12, byte(n))
}

func (rcv *Envelope) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func EnvelopeStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func EnvelopeAddProtocolVersion(builder *flatbuffers.Builder, protocolVersion uint32) {
	builder.PrependUint32Slot(0, protocolVersion, 0)
}
func EnvelopeAddClientVersion(builder *flatbuffers.Builder, clientVersion uint32) {
	builder.PrependUint32Slot(1, clientVersion, 0)
}
func EnvelopeAddMessageId(builder *flatbuffers.Builder, messageId uint64) {
	builder.PrependUint64Slot(2, messageId, 0)
}
func EnvelopeAddCorrelationId(builder *flatbuffers.Builder, correlationId uint64) {
	builder.PrependUint64Slot(3, correlationId, 0)
}
func EnvelopeAddPayloadType(builder *flatbuffers.Builder, payloadType Payload) {
	builder.PrependByteSlot(4, byte(payloadType), 0)
}
func EnvelopeAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(payload), 0)
}
func EnvelopeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
