// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import "strconv"

type ErrorCode byte

const (
	ErrorCodeINVALID_REQUEST      ErrorCode = 0
	ErrorCodeUNAUTHENTICATED      ErrorCode = 1
	ErrorCodePERMISSION_DENIED    ErrorCode = 2
	ErrorCodeNOT_FOUND            ErrorCode = 3
	ErrorCodeCONFLICT             ErrorCode = 4
	ErrorCodeRATE_LIMITED         ErrorCode = 5
	ErrorCodeUNSUPPORTED_PROTOCOL ErrorCode = 6
	ErrorCodeINTERNAL             ErrorCode = 7
	ErrorCodeSERVICE_UNAVAILABLE  ErrorCode = 8
)

var EnumNamesErrorCode = map[ErrorCode]string{
	ErrorCodeINVALID_REQUEST:      "INVALID_REQUEST",
	ErrorCodeUNAUTHENTICATED:      "UNAUTHENTICATED",
	ErrorCodePERMISSION_DENIED:    "PERMISSION_DENIED",
	ErrorCodeNOT_FOUND:            "NOT_FOUND",
	ErrorCodeCONFLICT:             "CONFLICT",
	ErrorCodeRATE_LIMITED:         "RATE_LIMITED",
	ErrorCodeUNSUPPORTED_PROTOCOL: "UNSUPPORTED_PROTOCOL",
	ErrorCodeINTERNAL:             "INTERNAL",
	ErrorCodeSERVICE_UNAVAILABLE:  "SERVICE_UNAVAILABLE",
}

var EnumValuesErrorCode = map[string]ErrorCode{
	"INVALID_REQUEST":      ErrorCodeINVALID_REQUEST,
	"UNAUTHENTICATED":      ErrorCodeUNAUTHENTICATED,
	"PERMISSION_DENIED":    ErrorCodePERMISSION_DENIED,
	"NOT_FOUND":            ErrorCodeNOT_FOUND,
	"CONFLICT":             ErrorCodeCONFLICT,
	"RATE_LIMITED":         ErrorCodeRATE_LIMITED,
	"UNSUPPORTED_PROTOCOL": ErrorCodeUNSUPPORTED_PROTOCOL,
	"INTERNAL":             ErrorCodeINTERNAL,
	"SERVICE_UNAVAILABLE":  ErrorCodeSERVICE_UNAVAILABLE,
}

func (v ErrorCode) String() string {
	if s, ok := EnumNamesErrorCode[v]; ok {
		return s
	}
	return "ErrorCode(" + strconv.FormatInt(int64(v), 10) + ")"
}
