// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Error struct {
	_tab flatbuffers.Table
}

func GetRootAsError(buf []byte, offset flatbuffers.UOffsetT) *Error {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Error{}
	x.Init(buf, n+offset)
	return x
}

func FinishErrorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsError(buf []byte, offset flatbuffers.UOffsetT) *Error {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Error{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedErrorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Error) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Error) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Error) Code() ErrorCode {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ErrorCode(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *Error) MutateCode(n ErrorCode) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *Error) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Error) Retryable() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Error) MutateRetryable(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func (rcv *Error) RetryAfterMs() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Error) MutateRetryAfterMs(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func ErrorStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ErrorAddCode(builder *flatbuffers.Builder, code ErrorCode) {
	builder.PrependByteSlot(0, byte(code), 0)
}
func ErrorAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(message), 0)
}
func ErrorAddRetryable(builder *flatbuffers.Builder, retryable bool) {
	builder.PrependBoolSlot(2, retryable, false)
}
func ErrorAddRetryAfterMs(builder *flatbuffers.Builder, retryAfterMs uint32) {
	builder.PrependUint32Slot(3, retryAfterMs, 0)
}
func ErrorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
