// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LogoutRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsLogoutRequest(buf []byte, offset flatbuffers.UOffsetT) *LogoutRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LogoutRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishLogoutRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLogoutRequest(buf []byte, offset flatbuffers.UOffsetT) *LogoutRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LogoutRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLogoutRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LogoutRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LogoutRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func LogoutRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func LogoutRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
