// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LogoutResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsLogoutResponse(buf []byte, offset flatbuffers.UOffsetT) *LogoutResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LogoutResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishLogoutResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLogoutResponse(buf []byte, offset flatbuffers.UOffsetT) *LogoutResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LogoutResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLogoutResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *LogoutResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LogoutResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LogoutResponse) SessionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func LogoutResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func LogoutResponseAddSessionId(builder *flatbuffers.Builder, sessionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(sessionId), 0)
}
func LogoutResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
