// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OtpLinkEmailVerified struct {
	_tab flatbuffers.Table
}

func GetRootAsOtpLinkEmailVerified(buf []byte, offset flatbuffers.UOffsetT) *OtpLinkEmailVerified {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OtpLinkEmailVerified{}
	x.Init(buf, n+offset)
	return x
}

func FinishOtpLinkEmailVerifiedBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOtpLinkEmailVerified(buf []byte, offset flatbuffers.UOffsetT) *OtpLinkEmailVerified {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OtpLinkEmailVerified{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOtpLinkEmailVerifiedBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OtpLinkEmailVerified) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OtpLinkEmailVerified) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OtpLinkEmailVerified) IdentityId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OtpLinkEmailVerified) Email() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OtpLinkEmailVerified) LinkedAtMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OtpLinkEmailVerified) MutateLinkedAtMs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func OtpLinkEmailVerifiedStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func OtpLinkEmailVerifiedAddIdentityId(builder *flatbuffers.Builder, identityId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(identityId), 0)
}
func OtpLinkEmailVerifiedAddEmail(builder *flatbuffers.Builder, email flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(email), 0)
}
func OtpLinkEmailVerifiedAddLinkedAtMs(builder *flatbuffers.Builder, linkedAtMs uint64) {
	builder.PrependUint64Slot(2, linkedAtMs, 0)
}
func OtpLinkEmailVerifiedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
