// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OtpLinkEmailVerify struct {
	_tab flatbuffers.Table
}

func GetRootAsOtpLinkEmailVerify(buf []byte, offset flatbuffers.UOffsetT) *OtpLinkEmailVerify {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OtpLinkEmailVerify{}
	x.Init(buf, n+offset)
	return x
}

func FinishOtpLinkEmailVerifyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOtpLinkEmailVerify(buf []byte, offset flatbuffers.UOffsetT) *OtpLinkEmailVerify {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OtpLinkEmailVerify{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOtpLinkEmailVerifyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OtpLinkEmailVerify) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OtpLinkEmailVerify) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OtpLinkEmailVerify) RequestId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OtpLinkEmailVerify) Code() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func OtpLinkEmailVerifyStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func OtpLinkEmailVerifyAddRequestId(builder *flatbuffers.Builder, requestId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(requestId), 0)
}
func OtpLinkEmailVerifyAddCode(builder *flatbuffers.Builder, code flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(code), 0)
}
func OtpLinkEmailVerifyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
