// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OtpLinkEmailAck struct {
	_tab flatbuffers.Table
}

func GetRootAsOtpLinkEmailAck(buf []byte, offset flatbuffers.UOffsetT) *OtpLinkEmailAck {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OtpLinkEmailAck{}
	x.Init(buf, n+offset)
	return x
}

func FinishOtpLinkEmailAckBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOtpLinkEmailAck(buf []byte, offset flatbuffers.UOffsetT) *OtpLinkEmailAck {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OtpLinkEmailAck{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOtpLinkEmailAckBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OtpLinkEmailAck) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OtpLinkEmailAck) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OtpLinkEmailAck) RequestId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *OtpLinkEmailAck) ExpiresAtMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OtpLinkEmailAck) MutateExpiresAtMs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func OtpLinkEmailAckStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func OtpLinkEmailAckAddRequestId(builder *flatbuffers.Builder, requestId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(requestId), 0)
}
func OtpLinkEmailAckAddExpiresAtMs(builder *flatbuffers.Builder, expiresAtMs uint64) {
	builder.PrependUint64Slot(1, expiresAtMs, 0)
}
func OtpLinkEmailAckEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
