// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OtpLinkEmailRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsOtpLinkEmailRequest(buf []byte, offset flatbuffers.UOffsetT) *OtpLinkEmailRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OtpLinkEmailRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishOtpLinkEmailRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsOtpLinkEmailRequest(buf []byte, offset flatbuffers.UOffsetT) *OtpLinkEmailRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &OtpLinkEmailRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedOtpLinkEmailRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *OtpLinkEmailRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OtpLinkEmailRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OtpLinkEmailRequest) Email() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func OtpLinkEmailRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func OtpLinkEmailRequestAddEmail(builder *flatbuffers.Builder, email flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(email), 0)
}
func OtpLinkEmailRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
