// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PasskeyRegisterOptionsResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsPasskeyRegisterOptionsResponse(buf []byte, offset flatbuffers.UOffsetT) *PasskeyRegisterOptionsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PasskeyRegisterOptionsResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishPasskeyRegisterOptionsResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPasskeyRegisterOptionsResponse(buf []byte, offset flatbuffers.UOffsetT) *PasskeyRegisterOptionsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PasskeyRegisterOptionsResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPasskeyRegisterOptionsResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PasskeyRegisterOptionsResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PasskeyRegisterOptionsResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PasskeyRegisterOptionsResponse) ChallengeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PasskeyRegisterOptionsResponse) OptionsJson() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PasskeyRegisterOptionsResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PasskeyRegisterOptionsResponseAddChallengeId(builder *flatbuffers.Builder, challengeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(challengeId), 0)
}
func PasskeyRegisterOptionsResponseAddOptionsJson(builder *flatbuffers.Builder, optionsJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(optionsJson), 0)
}
func PasskeyRegisterOptionsResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
