// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PasskeyListRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsPasskeyListRequest(buf []byte, offset flatbuffers.UOffsetT) *PasskeyListRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PasskeyListRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishPasskeyListRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPasskeyListRequest(buf []byte, offset flatbuffers.UOffsetT) *PasskeyListRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PasskeyListRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPasskeyListRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PasskeyListRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PasskeyListRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func PasskeyListRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func PasskeyListRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
