// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PasskeyRegisterVerifyRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsPasskeyRegisterVerifyRequest(buf []byte, offset flatbuffers.UOffsetT) *PasskeyRegisterVerifyRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PasskeyRegisterVerifyRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishPasskeyRegisterVerifyRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPasskeyRegisterVerifyRequest(buf []byte, offset flatbuffers.UOffsetT) *PasskeyRegisterVerifyRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PasskeyRegisterVerifyRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPasskeyRegisterVerifyRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PasskeyRegisterVerifyRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PasskeyRegisterVerifyRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PasskeyRegisterVerifyRequest) ChallengeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PasskeyRegisterVerifyRequest) ResponseJson() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PasskeyRegisterVerifyRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PasskeyRegisterVerifyRequestAddChallengeId(builder *flatbuffers.Builder, challengeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(challengeId), 0)
}
func PasskeyRegisterVerifyRequestAddResponseJson(builder *flatbuffers.Builder, responseJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(responseJson), 0)
}
func PasskeyRegisterVerifyRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
