// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PasskeyDeleteResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsPasskeyDeleteResponse(buf []byte, offset flatbuffers.UOffsetT) *PasskeyDeleteResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PasskeyDeleteResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishPasskeyDeleteResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPasskeyDeleteResponse(buf []byte, offset flatbuffers.UOffsetT) *PasskeyDeleteResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PasskeyDeleteResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPasskeyDeleteResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PasskeyDeleteResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PasskeyDeleteResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PasskeyDeleteResponse) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PasskeyDeleteResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PasskeyDeleteResponseAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func PasskeyDeleteResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
