// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PasskeyRegisterVerifyResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsPasskeyRegisterVerifyResponse(buf []byte, offset flatbuffers.UOffsetT) *PasskeyRegisterVerifyResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PasskeyRegisterVerifyResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishPasskeyRegisterVerifyResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPasskeyRegisterVerifyResponse(buf []byte, offset flatbuffers.UOffsetT) *PasskeyRegisterVerifyResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PasskeyRegisterVerifyResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPasskeyRegisterVerifyResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PasskeyRegisterVerifyResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PasskeyRegisterVerifyResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PasskeyRegisterVerifyResponse) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PasskeyRegisterVerifyResponse) CreatedAtMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PasskeyRegisterVerifyResponse) MutateCreatedAtMs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func PasskeyRegisterVerifyResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PasskeyRegisterVerifyResponseAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func PasskeyRegisterVerifyResponseAddCreatedAtMs(builder *flatbuffers.Builder, createdAtMs uint64) {
	builder.PrependUint64Slot(1, createdAtMs, 0)
}
func PasskeyRegisterVerifyResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
