// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PasskeyRegisterOptionsRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsPasskeyRegisterOptionsRequest(buf []byte, offset flatbuffers.UOffsetT) *PasskeyRegisterOptionsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PasskeyRegisterOptionsRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishPasskeyRegisterOptionsRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPasskeyRegisterOptionsRequest(buf []byte, offset flatbuffers.UOffsetT) *PasskeyRegisterOptionsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PasskeyRegisterOptionsRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPasskeyRegisterOptionsRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PasskeyRegisterOptionsRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PasskeyRegisterOptionsRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func PasskeyRegisterOptionsRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func PasskeyRegisterOptionsRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
