// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PasskeyInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsPasskeyInfo(buf []byte, offset flatbuffers.UOffsetT) *PasskeyInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PasskeyInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishPasskeyInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPasskeyInfo(buf []byte, offset flatbuffers.UOffsetT) *PasskeyInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PasskeyInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPasskeyInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PasskeyInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PasskeyInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PasskeyInfo) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PasskeyInfo) Aaguid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PasskeyInfo) Transports(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *PasskeyInfo) TransportsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PasskeyInfo) CreatedAtMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PasskeyInfo) MutateCreatedAtMs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *PasskeyInfo) LastUsedAtMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PasskeyInfo) MutateLastUsedAtMs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func PasskeyInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func PasskeyInfoAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func PasskeyInfoAddAaguid(builder *flatbuffers.Builder, aaguid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(aaguid), 0)
}
func PasskeyInfoAddTransports(builder *flatbuffers.Builder, transports flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(transports), 0)
}
func PasskeyInfoStartTransportsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PasskeyInfoAddCreatedAtMs(builder *flatbuffers.Builder, createdAtMs uint64) {
	builder.PrependUint64Slot(3, createdAtMs, 0)
}
func PasskeyInfoAddLastUsedAtMs(builder *flatbuffers.Builder, lastUsedAtMs uint64) {
	builder.PrependUint64Slot(4, lastUsedAtMs, 0)
}
func PasskeyInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
