// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PasskeyDeleteRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsPasskeyDeleteRequest(buf []byte, offset flatbuffers.UOffsetT) *PasskeyDeleteRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PasskeyDeleteRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishPasskeyDeleteRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPasskeyDeleteRequest(buf []byte, offset flatbuffers.UOffsetT) *PasskeyDeleteRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PasskeyDeleteRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPasskeyDeleteRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PasskeyDeleteRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PasskeyDeleteRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PasskeyDeleteRequest) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PasskeyDeleteRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PasskeyDeleteRequestAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func PasskeyDeleteRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
