// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import "strconv"

type Payload byte

const (
	PayloadNONE                 Payload = 0
	PayloadPing                 Payload = 1
	PayloadPong                 Payload = 2
	PayloadError                Payload = 3
	PayloadEmpty                Payload = 4
	PayloadTestEcho             Payload = 5
	PayloadOtpLinkEmailRequest  Payload = 6
	PayloadOtpLinkEmailAck      Payload = 7
	PayloadOtpLinkEmailVerify   Payload = 8
	PayloadOtpLinkEmailVerified Payload = 9
	PayloadSessionListRequest   Payload = 10
	PayloadSessionListResponse  Payload = 11
	PayloadLogoutRequest        Payload = 12
	PayloadLogoutResponse       Payload = 13
)

var EnumNamesPayload = map[Payload]string{
	PayloadNONE:                 "NONE",
	PayloadPing:                 "Ping",
	PayloadPong:                 "Pong",
	PayloadError:                "Error",
	PayloadEmpty:                "Empty",
	PayloadTestEcho:             "TestEcho",
	PayloadOtpLinkEmailRequest:  "OtpLinkEmailRequest",
	PayloadOtpLinkEmailAck:      "OtpLinkEmailAck",
	PayloadOtpLinkEmailVerify:   "OtpLinkEmailVerify",
	PayloadOtpLinkEmailVerified: "OtpLinkEmailVerified",
	PayloadSessionListRequest:   "SessionListRequest",
	PayloadSessionListResponse:  "SessionListResponse",
	PayloadLogoutRequest:        "LogoutRequest",
	PayloadLogoutResponse:       "LogoutResponse",
}

var EnumValuesPayload = map[string]Payload{
	"NONE":                 PayloadNONE,
	"Ping":                 PayloadPing,
	"Pong":                 PayloadPong,
	"Error":                PayloadError,
	"Empty":                PayloadEmpty,
	"TestEcho":             PayloadTestEcho,
	"OtpLinkEmailRequest":  PayloadOtpLinkEmailRequest,
	"OtpLinkEmailAck":      PayloadOtpLinkEmailAck,
	"OtpLinkEmailVerify":   PayloadOtpLinkEmailVerify,
	"OtpLinkEmailVerified": PayloadOtpLinkEmailVerified,
	"SessionListRequest":   PayloadSessionListRequest,
	"SessionListResponse":  PayloadSessionListResponse,
	"LogoutRequest":        PayloadLogoutRequest,
	"LogoutResponse":       PayloadLogoutResponse,
}

func (v Payload) String() string {
	if s, ok := EnumNamesPayload[v]; ok {
		return s
	}
	return "Payload(" + strconv.FormatInt(int64(v), 10) + ")"
}
