// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import "strconv"

type Payload byte

const (
	PayloadNONE     Payload = 0
	PayloadPing     Payload = 1
	PayloadPong     Payload = 2
	PayloadError    Payload = 3
	PayloadEmpty    Payload = 4
	PayloadTestEcho Payload = 5
)

var EnumNamesPayload = map[Payload]string{
	PayloadNONE:     "NONE",
	PayloadPing:     "Ping",
	PayloadPong:     "Pong",
	PayloadError:    "Error",
	PayloadEmpty:    "Empty",
	PayloadTestEcho: "TestEcho",
}

var EnumValuesPayload = map[string]Payload{
	"NONE":     PayloadNONE,
	"Ping":     PayloadPing,
	"Pong":     PayloadPong,
	"Error":    PayloadError,
	"Empty":    PayloadEmpty,
	"TestEcho": PayloadTestEcho,
}

func (v Payload) String() string {
	if s, ok := EnumNamesPayload[v]; ok {
		return s
	}
	return "Payload(" + strconv.FormatInt(int64(v), 10) + ")"
}
