// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SessionRevokeResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSessionRevokeResponse(buf []byte, offset flatbuffers.UOffsetT) *SessionRevokeResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SessionRevokeResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishSessionRevokeResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSessionRevokeResponse(buf []byte, offset flatbuffers.UOffsetT) *SessionRevokeResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SessionRevokeResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSessionRevokeResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SessionRevokeResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SessionRevokeResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SessionRevokeResponse) SessionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SessionRevokeResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SessionRevokeResponseAddSessionId(builder *flatbuffers.Builder, sessionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(sessionId), 0)
}
func SessionRevokeResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
