// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SessionRevokeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSessionRevokeRequest(buf []byte, offset flatbuffers.UOffsetT) *SessionRevokeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SessionRevokeRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSessionRevokeRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSessionRevokeRequest(buf []byte, offset flatbuffers.UOffsetT) *SessionRevokeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SessionRevokeRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSessionRevokeRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SessionRevokeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SessionRevokeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SessionRevokeRequest) SessionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SessionRevokeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SessionRevokeRequestAddSessionId(builder *flatbuffers.Builder, sessionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(sessionId), 0)
}
func SessionRevokeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
