// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SessionRevokeAllRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSessionRevokeAllRequest(buf []byte, offset flatbuffers.UOffsetT) *SessionRevokeAllRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SessionRevokeAllRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSessionRevokeAllRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSessionRevokeAllRequest(buf []byte, offset flatbuffers.UOffsetT) *SessionRevokeAllRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SessionRevokeAllRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSessionRevokeAllRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SessionRevokeAllRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SessionRevokeAllRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func SessionRevokeAllRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SessionRevokeAllRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
