// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SessionInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsSessionInfo(buf []byte, offset flatbuffers.UOffsetT) *SessionInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SessionInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishSessionInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSessionInfo(buf []byte, offset flatbuffers.UOffsetT) *SessionInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SessionInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSessionInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SessionInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SessionInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SessionInfo) SessionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SessionInfo) DeviceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SessionInfo) Platform() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SessionInfo) Ip() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SessionInfo) CreatedAtMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SessionInfo) MutateCreatedAtMs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *SessionInfo) ExpiresAtMs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SessionInfo) MutateExpiresAtMs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func (rcv *SessionInfo) IsCurrent() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SessionInfo) MutateIsCurrent(n bool) bool {
	return rcv._tab.MutateBoolSlot(16, n)
}

func SessionInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func SessionInfoAddSessionId(builder *flatbuffers.Builder, sessionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(sessionId), 0)
}
func SessionInfoAddDeviceId(builder *flatbuffers.Builder, deviceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(deviceId), 0)
}
func SessionInfoAddPlatform(builder *flatbuffers.Builder, platform flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(platform), 0)
}
func SessionInfoAddIp(builder *flatbuffers.Builder, ip flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(ip), 0)
}
func SessionInfoAddCreatedAtMs(builder *flatbuffers.Builder, createdAtMs uint64) {
	builder.PrependUint64Slot(4, createdAtMs, 0)
}
func SessionInfoAddExpiresAtMs(builder *flatbuffers.Builder, expiresAtMs uint64) {
	builder.PrependUint64Slot(5, expiresAtMs, 0)
}
func SessionInfoAddIsCurrent(builder *flatbuffers.Builder, isCurrent bool) {
	builder.PrependBoolSlot(6, isCurrent, false)
}
func SessionInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
