// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SessionRevokeAllResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSessionRevokeAllResponse(buf []byte, offset flatbuffers.UOffsetT) *SessionRevokeAllResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SessionRevokeAllResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishSessionRevokeAllResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSessionRevokeAllResponse(buf []byte, offset flatbuffers.UOffsetT) *SessionRevokeAllResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SessionRevokeAllResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSessionRevokeAllResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SessionRevokeAllResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SessionRevokeAllResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SessionRevokeAllResponse) Status() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SessionRevokeAllResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SessionRevokeAllResponseAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(status), 0)
}
func SessionRevokeAllResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
