// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SessionListRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSessionListRequest(buf []byte, offset flatbuffers.UOffsetT) *SessionListRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SessionListRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishSessionListRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSessionListRequest(buf []byte, offset flatbuffers.UOffsetT) *SessionListRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SessionListRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSessionListRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SessionListRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SessionListRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func SessionListRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SessionListRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
