// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TestEcho struct {
	_tab flatbuffers.Table
}

func GetRootAsTestEcho(buf []byte, offset flatbuffers.UOffsetT) *TestEcho {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TestEcho{}
	x.Init(buf, n+offset)
	return x
}

func FinishTestEchoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTestEcho(buf []byte, offset flatbuffers.UOffsetT) *TestEcho {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TestEcho{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTestEchoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TestEcho) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TestEcho) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TestEcho) Data() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TestEchoStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TestEchoAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data), 0)
}
func TestEchoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
