// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package ws

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserProfileRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsUserProfileRequest(buf []byte, offset flatbuffers.UOffsetT) *UserProfileRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserProfileRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishUserProfileRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUserProfileRequest(buf []byte, offset flatbuffers.UOffsetT) *UserProfileRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserProfileRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUserProfileRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UserProfileRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserProfileRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func UserProfileRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func UserProfileRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
