package wireauthgrpc

import (
	"time"

	"google.golang.org/grpc/credentials"
)

// authType is returned by SessionAuthInfo.AuthType(), the credentials.AuthInfo
// method gRPC/interceptors use to identify which transport security
// mechanism established a connection.
const authType = "wireauthgrpc"

// SessionAuthInfo carries per-connection facts derived from a completed
// handshake. It is attached to the context via gRPC's peer package and
// retrievable in interceptors / handlers with:
//
//	p, ok := peer.FromContext(ctx)
//	if ok {
//	    info, ok := p.AuthInfo.(wireauthgrpc.SessionAuthInfo)
//	}
//
// It intentionally does not carry the session's AES key or any other
// secret material — AuthInfo values can end up in logs or debug tooling,
// so only non-secret session metadata belongs here.
type SessionAuthInfo struct {
	// ServerNonce is the 16-byte nonce generated by the server during
	// stage 1. Both sides know it; it is not secret on its own (secrecy
	// comes from the ECDH shared secret), but it is useful as a
	// correlation ID for a given connection's handshake, and resume-proof
	// flows (see wireauth's VerifyResumeProof) key off of it.
	ServerNonce []byte

	// EstablishedAt is when the handshake completed and secureConn began
	// serving traffic.
	EstablishedAt time.Time
}

// AuthType implements credentials.AuthInfo.
func (SessionAuthInfo) AuthType() string { return authType }

var _ credentials.AuthInfo = SessionAuthInfo{}
