// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClientContextT struct {
	Platform   Platform `json:"platform"`
	Os         string   `json:"os"`
	DeviceName string   `json:"device_name"`
	UserAgent  string   `json:"user_agent"`
}

func (t *ClientContextT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	osOffset := builder.CreateString(t.Os)
	deviceNameOffset := builder.CreateString(t.DeviceName)
	userAgentOffset := builder.CreateString(t.UserAgent)
	ClientContextStart(builder)
	ClientContextAddPlatform(builder, t.Platform)
	ClientContextAddOs(builder, osOffset)
	ClientContextAddDeviceName(builder, deviceNameOffset)
	ClientContextAddUserAgent(builder, userAgentOffset)
	return ClientContextEnd(builder)
}

func (rcv *ClientContext) UnPackTo(t *ClientContextT) {
	t.Platform = rcv.Platform()
	t.Os = string(rcv.Os())
	t.DeviceName = string(rcv.DeviceName())
	t.UserAgent = string(rcv.UserAgent())
}

func (rcv *ClientContext) UnPack() *ClientContextT {
	if rcv == nil {
		return nil
	}
	t := &ClientContextT{}
	rcv.UnPackTo(t)
	return t
}

type ClientContext struct {
	_tab flatbuffers.Table
}

func GetRootAsClientContext(buf []byte, offset flatbuffers.UOffsetT) *ClientContext {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClientContext{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsClientContext(buf []byte, offset flatbuffers.UOffsetT) *ClientContext {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ClientContext{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ClientContext) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClientContext) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ClientContext) Platform() Platform {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return Platform(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ClientContext) MutatePlatform(n Platform) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *ClientContext) Os() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientContext) DeviceName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientContext) UserAgent() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ClientContextStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ClientContextAddPlatform(builder *flatbuffers.Builder, platform Platform) {
	builder.PrependInt8Slot(0, int8(platform), 0)
}
func ClientContextAddOs(builder *flatbuffers.Builder, os flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(os), 0)
}
func ClientContextAddDeviceName(builder *flatbuffers.Builder, deviceName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(deviceName), 0)
}
func ClientContextAddUserAgent(builder *flatbuffers.Builder, userAgent flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(userAgent), 0)
}
func ClientContextEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
