// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConfirmQRLoginRequestT struct {
	Token string `json:"token"`
}

func (t *ConfirmQRLoginRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	tokenOffset := builder.CreateString(t.Token)
	ConfirmQRLoginRequestStart(builder)
	ConfirmQRLoginRequestAddToken(builder, tokenOffset)
	return ConfirmQRLoginRequestEnd(builder)
}

func (rcv *ConfirmQRLoginRequest) UnPackTo(t *ConfirmQRLoginRequestT) {
	t.Token = string(rcv.Token())
}

func (rcv *ConfirmQRLoginRequest) UnPack() *ConfirmQRLoginRequestT {
	if rcv == nil {
		return nil
	}
	t := &ConfirmQRLoginRequestT{}
	rcv.UnPackTo(t)
	return t
}

type ConfirmQRLoginRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsConfirmQRLoginRequest(buf []byte, offset flatbuffers.UOffsetT) *ConfirmQRLoginRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConfirmQRLoginRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsConfirmQRLoginRequest(buf []byte, offset flatbuffers.UOffsetT) *ConfirmQRLoginRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConfirmQRLoginRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ConfirmQRLoginRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConfirmQRLoginRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConfirmQRLoginRequest) Token() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ConfirmQRLoginRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ConfirmQRLoginRequestAddToken(builder *flatbuffers.Builder, token flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(token), 0)
}
func ConfirmQRLoginRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
