// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConfirmQRLoginResponseT struct {
	Ok         bool              `json:"ok"`
	FailReason QRLoginFailReason `json:"fail_reason"`
}

func (t *ConfirmQRLoginResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	ConfirmQRLoginResponseStart(builder)
	ConfirmQRLoginResponseAddOk(builder, t.Ok)
	ConfirmQRLoginResponseAddFailReason(builder, t.FailReason)
	return ConfirmQRLoginResponseEnd(builder)
}

func (rcv *ConfirmQRLoginResponse) UnPackTo(t *ConfirmQRLoginResponseT) {
	t.Ok = rcv.Ok()
	t.FailReason = rcv.FailReason()
}

func (rcv *ConfirmQRLoginResponse) UnPack() *ConfirmQRLoginResponseT {
	if rcv == nil {
		return nil
	}
	t := &ConfirmQRLoginResponseT{}
	rcv.UnPackTo(t)
	return t
}

type ConfirmQRLoginResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsConfirmQRLoginResponse(buf []byte, offset flatbuffers.UOffsetT) *ConfirmQRLoginResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConfirmQRLoginResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsConfirmQRLoginResponse(buf []byte, offset flatbuffers.UOffsetT) *ConfirmQRLoginResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConfirmQRLoginResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ConfirmQRLoginResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConfirmQRLoginResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConfirmQRLoginResponse) Ok() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ConfirmQRLoginResponse) MutateOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *ConfirmQRLoginResponse) FailReason() QRLoginFailReason {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return QRLoginFailReason(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ConfirmQRLoginResponse) MutateFailReason(n QRLoginFailReason) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func ConfirmQRLoginResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ConfirmQRLoginResponseAddOk(builder *flatbuffers.Builder, ok bool) {
	builder.PrependBoolSlot(0, ok, false)
}
func ConfirmQRLoginResponseAddFailReason(builder *flatbuffers.Builder, failReason QRLoginFailReason) {
	builder.PrependInt8Slot(1, int8(failReason), 0)
}
func ConfirmQRLoginResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
