// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GenerateQRLoginRequestT struct {
	ClientCtx *ClientContextT `json:"client_ctx"`
}

func (t *GenerateQRLoginRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	clientCtxOffset := t.ClientCtx.Pack(builder)
	GenerateQRLoginRequestStart(builder)
	GenerateQRLoginRequestAddClientCtx(builder, clientCtxOffset)
	return GenerateQRLoginRequestEnd(builder)
}

func (rcv *GenerateQRLoginRequest) UnPackTo(t *GenerateQRLoginRequestT) {
	t.ClientCtx = rcv.ClientCtx(nil).UnPack()
}

func (rcv *GenerateQRLoginRequest) UnPack() *GenerateQRLoginRequestT {
	if rcv == nil {
		return nil
	}
	t := &GenerateQRLoginRequestT{}
	rcv.UnPackTo(t)
	return t
}

type GenerateQRLoginRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsGenerateQRLoginRequest(buf []byte, offset flatbuffers.UOffsetT) *GenerateQRLoginRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GenerateQRLoginRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsGenerateQRLoginRequest(buf []byte, offset flatbuffers.UOffsetT) *GenerateQRLoginRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GenerateQRLoginRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *GenerateQRLoginRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GenerateQRLoginRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GenerateQRLoginRequest) ClientCtx(obj *ClientContext) *ClientContext {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ClientContext)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func GenerateQRLoginRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GenerateQRLoginRequestAddClientCtx(builder *flatbuffers.Builder, clientCtx flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(clientCtx), 0)
}
func GenerateQRLoginRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
