// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GenerateQRLoginResponseT struct {
	Token       string `json:"token"`
	ExpiresAtMs int64  `json:"expires_at_ms"`
}

func (t *GenerateQRLoginResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	tokenOffset := builder.CreateString(t.Token)
	GenerateQRLoginResponseStart(builder)
	GenerateQRLoginResponseAddToken(builder, tokenOffset)
	GenerateQRLoginResponseAddExpiresAtMs(builder, t.ExpiresAtMs)
	return GenerateQRLoginResponseEnd(builder)
}

func (rcv *GenerateQRLoginResponse) UnPackTo(t *GenerateQRLoginResponseT) {
	t.Token = string(rcv.Token())
	t.ExpiresAtMs = rcv.ExpiresAtMs()
}

func (rcv *GenerateQRLoginResponse) UnPack() *GenerateQRLoginResponseT {
	if rcv == nil {
		return nil
	}
	t := &GenerateQRLoginResponseT{}
	rcv.UnPackTo(t)
	return t
}

type GenerateQRLoginResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsGenerateQRLoginResponse(buf []byte, offset flatbuffers.UOffsetT) *GenerateQRLoginResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GenerateQRLoginResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsGenerateQRLoginResponse(buf []byte, offset flatbuffers.UOffsetT) *GenerateQRLoginResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GenerateQRLoginResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *GenerateQRLoginResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GenerateQRLoginResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GenerateQRLoginResponse) Token() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GenerateQRLoginResponse) ExpiresAtMs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GenerateQRLoginResponse) MutateExpiresAtMs(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func GenerateQRLoginResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GenerateQRLoginResponseAddToken(builder *flatbuffers.Builder, token flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(token), 0)
}
func GenerateQRLoginResponseAddExpiresAtMs(builder *flatbuffers.Builder, expiresAtMs int64) {
	builder.PrependInt64Slot(1, expiresAtMs, 0)
}
func GenerateQRLoginResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
