// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KillSessionResponseT struct {
	Ok bool `json:"ok"`
}

func (t *KillSessionResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	KillSessionResponseStart(builder)
	KillSessionResponseAddOk(builder, t.Ok)
	return KillSessionResponseEnd(builder)
}

func (rcv *KillSessionResponse) UnPackTo(t *KillSessionResponseT) {
	t.Ok = rcv.Ok()
}

func (rcv *KillSessionResponse) UnPack() *KillSessionResponseT {
	if rcv == nil {
		return nil
	}
	t := &KillSessionResponseT{}
	rcv.UnPackTo(t)
	return t
}

type KillSessionResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsKillSessionResponse(buf []byte, offset flatbuffers.UOffsetT) *KillSessionResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KillSessionResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsKillSessionResponse(buf []byte, offset flatbuffers.UOffsetT) *KillSessionResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KillSessionResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *KillSessionResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KillSessionResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KillSessionResponse) Ok() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *KillSessionResponse) MutateOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func KillSessionResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func KillSessionResponseAddOk(builder *flatbuffers.Builder, ok bool) {
	builder.PrependBoolSlot(0, ok, false)
}
func KillSessionResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
