// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KillSessionRequestT struct {
	AuthKeyId uint64 `json:"auth_key_id"`
}

func (t *KillSessionRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	KillSessionRequestStart(builder)
	KillSessionRequestAddAuthKeyId(builder, t.AuthKeyId)
	return KillSessionRequestEnd(builder)
}

func (rcv *KillSessionRequest) UnPackTo(t *KillSessionRequestT) {
	t.AuthKeyId = rcv.AuthKeyId()
}

func (rcv *KillSessionRequest) UnPack() *KillSessionRequestT {
	if rcv == nil {
		return nil
	}
	t := &KillSessionRequestT{}
	rcv.UnPackTo(t)
	return t
}

type KillSessionRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsKillSessionRequest(buf []byte, offset flatbuffers.UOffsetT) *KillSessionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KillSessionRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsKillSessionRequest(buf []byte, offset flatbuffers.UOffsetT) *KillSessionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KillSessionRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *KillSessionRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KillSessionRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KillSessionRequest) AuthKeyId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KillSessionRequest) MutateAuthKeyId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func KillSessionRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func KillSessionRequestAddAuthKeyId(builder *flatbuffers.Builder, authKeyId uint64) {
	builder.PrependUint64Slot(0, authKeyId, 0)
}
func KillSessionRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
