// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ListSessionsRequestT struct {
}

func (t *ListSessionsRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	ListSessionsRequestStart(builder)
	return ListSessionsRequestEnd(builder)
}

func (rcv *ListSessionsRequest) UnPackTo(t *ListSessionsRequestT) {
}

func (rcv *ListSessionsRequest) UnPack() *ListSessionsRequestT {
	if rcv == nil {
		return nil
	}
	t := &ListSessionsRequestT{}
	rcv.UnPackTo(t)
	return t
}

type ListSessionsRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsListSessionsRequest(buf []byte, offset flatbuffers.UOffsetT) *ListSessionsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ListSessionsRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsListSessionsRequest(buf []byte, offset flatbuffers.UOffsetT) *ListSessionsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ListSessionsRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ListSessionsRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ListSessionsRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func ListSessionsRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ListSessionsRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
