// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ListSessionsResponseT struct {
	Sessions []*SessionInfoT `json:"sessions"`
}

func (t *ListSessionsResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	sessionsOffset := flatbuffers.UOffsetT(0)
	if t.Sessions != nil {
		sessionsLength := len(t.Sessions)
		sessionsOffsets := make([]flatbuffers.UOffsetT, sessionsLength)
		for j := 0; j < sessionsLength; j++ {
			sessionsOffsets[j] = t.Sessions[j].Pack(builder)
		}
		ListSessionsResponseStartSessionsVector(builder, sessionsLength)
		for j := sessionsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(sessionsOffsets[j])
		}
		sessionsOffset = builder.EndVector(sessionsLength)
	}
	ListSessionsResponseStart(builder)
	ListSessionsResponseAddSessions(builder, sessionsOffset)
	return ListSessionsResponseEnd(builder)
}

func (rcv *ListSessionsResponse) UnPackTo(t *ListSessionsResponseT) {
	sessionsLength := rcv.SessionsLength()
	t.Sessions = make([]*SessionInfoT, sessionsLength)
	for j := 0; j < sessionsLength; j++ {
		x := SessionInfo{}
		rcv.Sessions(&x, j)
		t.Sessions[j] = x.UnPack()
	}
}

func (rcv *ListSessionsResponse) UnPack() *ListSessionsResponseT {
	if rcv == nil {
		return nil
	}
	t := &ListSessionsResponseT{}
	rcv.UnPackTo(t)
	return t
}

type ListSessionsResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsListSessionsResponse(buf []byte, offset flatbuffers.UOffsetT) *ListSessionsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ListSessionsResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsListSessionsResponse(buf []byte, offset flatbuffers.UOffsetT) *ListSessionsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ListSessionsResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ListSessionsResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ListSessionsResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ListSessionsResponse) Sessions(obj *SessionInfo, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ListSessionsResponse) SessionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ListSessionsResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ListSessionsResponseAddSessions(builder *flatbuffers.Builder, sessions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(sessions), 0)
}
func ListSessionsResponseStartSessionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ListSessionsResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
