// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LoginByGithubResponseT struct {
	AuthKeyId    uint64 `json:"auth_key_id"`
	UserId       int32  `json:"user_id"`
	ResumeSecret string `json:"resume_secret"`
}

func (t *LoginByGithubResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	resumeSecretOffset := builder.CreateString(t.ResumeSecret)
	LoginByGithubResponseStart(builder)
	LoginByGithubResponseAddAuthKeyId(builder, t.AuthKeyId)
	LoginByGithubResponseAddUserId(builder, t.UserId)
	LoginByGithubResponseAddResumeSecret(builder, resumeSecretOffset)
	return LoginByGithubResponseEnd(builder)
}

func (rcv *LoginByGithubResponse) UnPackTo(t *LoginByGithubResponseT) {
	t.AuthKeyId = rcv.AuthKeyId()
	t.UserId = rcv.UserId()
	t.ResumeSecret = string(rcv.ResumeSecret())
}

func (rcv *LoginByGithubResponse) UnPack() *LoginByGithubResponseT {
	if rcv == nil {
		return nil
	}
	t := &LoginByGithubResponseT{}
	rcv.UnPackTo(t)
	return t
}

type LoginByGithubResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsLoginByGithubResponse(buf []byte, offset flatbuffers.UOffsetT) *LoginByGithubResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LoginByGithubResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsLoginByGithubResponse(buf []byte, offset flatbuffers.UOffsetT) *LoginByGithubResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LoginByGithubResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *LoginByGithubResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LoginByGithubResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LoginByGithubResponse) AuthKeyId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LoginByGithubResponse) MutateAuthKeyId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *LoginByGithubResponse) UserId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *LoginByGithubResponse) MutateUserId(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *LoginByGithubResponse) ResumeSecret() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func LoginByGithubResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func LoginByGithubResponseAddAuthKeyId(builder *flatbuffers.Builder, authKeyId uint64) {
	builder.PrependUint64Slot(0, authKeyId, 0)
}
func LoginByGithubResponseAddUserId(builder *flatbuffers.Builder, userId int32) {
	builder.PrependInt32Slot(1, userId, 0)
}
func LoginByGithubResponseAddResumeSecret(builder *flatbuffers.Builder, resumeSecret flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(resumeSecret), 0)
}
func LoginByGithubResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
