// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LoginByGithubRequestT struct {
	Code      string          `json:"code"`
	ClientCtx *ClientContextT `json:"client_ctx"`
}

func (t *LoginByGithubRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	codeOffset := builder.CreateString(t.Code)
	clientCtxOffset := t.ClientCtx.Pack(builder)
	LoginByGithubRequestStart(builder)
	LoginByGithubRequestAddCode(builder, codeOffset)
	LoginByGithubRequestAddClientCtx(builder, clientCtxOffset)
	return LoginByGithubRequestEnd(builder)
}

func (rcv *LoginByGithubRequest) UnPackTo(t *LoginByGithubRequestT) {
	t.Code = string(rcv.Code())
	t.ClientCtx = rcv.ClientCtx(nil).UnPack()
}

func (rcv *LoginByGithubRequest) UnPack() *LoginByGithubRequestT {
	if rcv == nil {
		return nil
	}
	t := &LoginByGithubRequestT{}
	rcv.UnPackTo(t)
	return t
}

type LoginByGithubRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsLoginByGithubRequest(buf []byte, offset flatbuffers.UOffsetT) *LoginByGithubRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LoginByGithubRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsLoginByGithubRequest(buf []byte, offset flatbuffers.UOffsetT) *LoginByGithubRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LoginByGithubRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *LoginByGithubRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LoginByGithubRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *LoginByGithubRequest) Code() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *LoginByGithubRequest) ClientCtx(obj *ClientContext) *ClientContext {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ClientContext)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func LoginByGithubRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func LoginByGithubRequestAddCode(builder *flatbuffers.Builder, code flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(code), 0)
}
func LoginByGithubRequestAddClientCtx(builder *flatbuffers.Builder, clientCtx flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(clientCtx), 0)
}
func LoginByGithubRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
