// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import "strconv"

type Platform int8

const (
	PlatformUnknown Platform = 0
	PlatformWeb     Platform = 1
	PlatformIOS     Platform = 2
	PlatformAndroid Platform = 3
	PlatformMacOS   Platform = 4
)

var EnumNamesPlatform = map[Platform]string{
	PlatformUnknown: "Unknown",
	PlatformWeb:     "Web",
	PlatformIOS:     "IOS",
	PlatformAndroid: "Android",
	PlatformMacOS:   "MacOS",
}

var EnumValuesPlatform = map[string]Platform{
	"Unknown": PlatformUnknown,
	"Web":     PlatformWeb,
	"IOS":     PlatformIOS,
	"Android": PlatformAndroid,
	"MacOS":   PlatformMacOS,
}

func (v Platform) String() string {
	if s, ok := EnumNamesPlatform[v]; ok {
		return s
	}
	return "Platform(" + strconv.FormatInt(int64(v), 10) + ")"
}
