// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import "strconv"

type QRLoginFailReason int8

const (
	QRLoginFailReasonUnknown      QRLoginFailReason = 0
	QRLoginFailReasonTokenExpired QRLoginFailReason = 1
	QRLoginFailReasonAlreadyUsed  QRLoginFailReason = 2
	QRLoginFailReasonNotFound     QRLoginFailReason = 3
)

var EnumNamesQRLoginFailReason = map[QRLoginFailReason]string{
	QRLoginFailReasonUnknown:      "Unknown",
	QRLoginFailReasonTokenExpired: "TokenExpired",
	QRLoginFailReasonAlreadyUsed:  "AlreadyUsed",
	QRLoginFailReasonNotFound:     "NotFound",
}

var EnumValuesQRLoginFailReason = map[string]QRLoginFailReason{
	"Unknown":      QRLoginFailReasonUnknown,
	"TokenExpired": QRLoginFailReasonTokenExpired,
	"AlreadyUsed":  QRLoginFailReasonAlreadyUsed,
	"NotFound":     QRLoginFailReasonNotFound,
}

func (v QRLoginFailReason) String() string {
	if s, ok := EnumNamesQRLoginFailReason[v]; ok {
		return s
	}
	return "QRLoginFailReason(" + strconv.FormatInt(int64(v), 10) + ")"
}
