// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type QRLoginExpiredOrRejectedT struct {
	Reason QRLoginFailReason `json:"reason"`
}

func (t *QRLoginExpiredOrRejectedT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	QRLoginExpiredOrRejectedStart(builder)
	QRLoginExpiredOrRejectedAddReason(builder, t.Reason)
	return QRLoginExpiredOrRejectedEnd(builder)
}

func (rcv *QRLoginExpiredOrRejected) UnPackTo(t *QRLoginExpiredOrRejectedT) {
	t.Reason = rcv.Reason()
}

func (rcv *QRLoginExpiredOrRejected) UnPack() *QRLoginExpiredOrRejectedT {
	if rcv == nil {
		return nil
	}
	t := &QRLoginExpiredOrRejectedT{}
	rcv.UnPackTo(t)
	return t
}

type QRLoginExpiredOrRejected struct {
	_tab flatbuffers.Table
}

func GetRootAsQRLoginExpiredOrRejected(buf []byte, offset flatbuffers.UOffsetT) *QRLoginExpiredOrRejected {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &QRLoginExpiredOrRejected{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsQRLoginExpiredOrRejected(buf []byte, offset flatbuffers.UOffsetT) *QRLoginExpiredOrRejected {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &QRLoginExpiredOrRejected{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *QRLoginExpiredOrRejected) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *QRLoginExpiredOrRejected) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *QRLoginExpiredOrRejected) Reason() QRLoginFailReason {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return QRLoginFailReason(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *QRLoginExpiredOrRejected) MutateReason(n QRLoginFailReason) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func QRLoginExpiredOrRejectedStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func QRLoginExpiredOrRejectedAddReason(builder *flatbuffers.Builder, reason QRLoginFailReason) {
	builder.PrependInt8Slot(0, int8(reason), 0)
}
func QRLoginExpiredOrRejectedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
