// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type QRLoginConfirmedT struct {
	AuthKeyId    uint64 `json:"auth_key_id"`
	ResumeSecret string `json:"resume_secret"`
	UserId       int32  `json:"user_id"`
}

func (t *QRLoginConfirmedT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	resumeSecretOffset := builder.CreateString(t.ResumeSecret)
	QRLoginConfirmedStart(builder)
	QRLoginConfirmedAddAuthKeyId(builder, t.AuthKeyId)
	QRLoginConfirmedAddResumeSecret(builder, resumeSecretOffset)
	QRLoginConfirmedAddUserId(builder, t.UserId)
	return QRLoginConfirmedEnd(builder)
}

func (rcv *QRLoginConfirmed) UnPackTo(t *QRLoginConfirmedT) {
	t.AuthKeyId = rcv.AuthKeyId()
	t.ResumeSecret = string(rcv.ResumeSecret())
	t.UserId = rcv.UserId()
}

func (rcv *QRLoginConfirmed) UnPack() *QRLoginConfirmedT {
	if rcv == nil {
		return nil
	}
	t := &QRLoginConfirmedT{}
	rcv.UnPackTo(t)
	return t
}

type QRLoginConfirmed struct {
	_tab flatbuffers.Table
}

func GetRootAsQRLoginConfirmed(buf []byte, offset flatbuffers.UOffsetT) *QRLoginConfirmed {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &QRLoginConfirmed{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsQRLoginConfirmed(buf []byte, offset flatbuffers.UOffsetT) *QRLoginConfirmed {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &QRLoginConfirmed{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *QRLoginConfirmed) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *QRLoginConfirmed) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *QRLoginConfirmed) AuthKeyId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *QRLoginConfirmed) MutateAuthKeyId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *QRLoginConfirmed) ResumeSecret() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *QRLoginConfirmed) UserId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *QRLoginConfirmed) MutateUserId(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func QRLoginConfirmedStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func QRLoginConfirmedAddAuthKeyId(builder *flatbuffers.Builder, authKeyId uint64) {
	builder.PrependUint64Slot(0, authKeyId, 0)
}
func QRLoginConfirmedAddResumeSecret(builder *flatbuffers.Builder, resumeSecret flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(resumeSecret), 0)
}
func QRLoginConfirmedAddUserId(builder *flatbuffers.Builder, userId int32) {
	builder.PrependInt32Slot(2, userId, 0)
}
func QRLoginConfirmedEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
