// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type QRLoginEventT struct {
	Payload *QRLoginEventPayloadT `json:"payload"`
}

func (t *QRLoginEventT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	payloadOffset := t.Payload.Pack(builder)

	QRLoginEventStart(builder)
	if t.Payload != nil {
		QRLoginEventAddPayloadType(builder, t.Payload.Type)
	}
	QRLoginEventAddPayload(builder, payloadOffset)
	return QRLoginEventEnd(builder)
}

func (rcv *QRLoginEvent) UnPackTo(t *QRLoginEventT) {
	payloadTable := flatbuffers.Table{}
	if rcv.Payload(&payloadTable) {
		t.Payload = rcv.PayloadType().UnPack(payloadTable)
	}
}

func (rcv *QRLoginEvent) UnPack() *QRLoginEventT {
	if rcv == nil {
		return nil
	}
	t := &QRLoginEventT{}
	rcv.UnPackTo(t)
	return t
}

type QRLoginEvent struct {
	_tab flatbuffers.Table
}

func GetRootAsQRLoginEvent(buf []byte, offset flatbuffers.UOffsetT) *QRLoginEvent {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &QRLoginEvent{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsQRLoginEvent(buf []byte, offset flatbuffers.UOffsetT) *QRLoginEvent {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &QRLoginEvent{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *QRLoginEvent) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *QRLoginEvent) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *QRLoginEvent) PayloadType() QRLoginEventPayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return QRLoginEventPayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *QRLoginEvent) MutatePayloadType(n QRLoginEventPayload) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *QRLoginEvent) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func QRLoginEventStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func QRLoginEventAddPayloadType(builder *flatbuffers.Builder, payloadType QRLoginEventPayload) {
	builder.PrependByteSlot(0, byte(payloadType), 0)
}
func QRLoginEventAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(payload), 0)
}
func QRLoginEventEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
