// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	"strconv"

	flatbuffers "github.com/google/flatbuffers/go"
)

type QRLoginEventPayload byte

const (
	QRLoginEventPayloadNONE                     QRLoginEventPayload = 0
	QRLoginEventPayloadQRLoginConfirmed         QRLoginEventPayload = 1
	QRLoginEventPayloadQRLoginExpiredOrRejected QRLoginEventPayload = 2
)

var EnumNamesQRLoginEventPayload = map[QRLoginEventPayload]string{
	QRLoginEventPayloadNONE:                     "NONE",
	QRLoginEventPayloadQRLoginConfirmed:         "QRLoginConfirmed",
	QRLoginEventPayloadQRLoginExpiredOrRejected: "QRLoginExpiredOrRejected",
}

var EnumValuesQRLoginEventPayload = map[string]QRLoginEventPayload{
	"NONE":                     QRLoginEventPayloadNONE,
	"QRLoginConfirmed":         QRLoginEventPayloadQRLoginConfirmed,
	"QRLoginExpiredOrRejected": QRLoginEventPayloadQRLoginExpiredOrRejected,
}

func (v QRLoginEventPayload) String() string {
	if s, ok := EnumNamesQRLoginEventPayload[v]; ok {
		return s
	}
	return "QRLoginEventPayload(" + strconv.FormatInt(int64(v), 10) + ")"
}

type QRLoginEventPayloadT struct {
	Type  QRLoginEventPayload
	Value interface{}
}

func (t *QRLoginEventPayloadT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	switch t.Type {
	case QRLoginEventPayloadQRLoginConfirmed:
		return t.Value.(*QRLoginConfirmedT).Pack(builder)
	case QRLoginEventPayloadQRLoginExpiredOrRejected:
		return t.Value.(*QRLoginExpiredOrRejectedT).Pack(builder)
	}
	return 0
}

func (rcv QRLoginEventPayload) UnPack(table flatbuffers.Table) *QRLoginEventPayloadT {
	switch rcv {
	case QRLoginEventPayloadQRLoginConfirmed:
		x := QRLoginConfirmed{_tab: table}
		return &QRLoginEventPayloadT{Type: QRLoginEventPayloadQRLoginConfirmed, Value: x.UnPack()}
	case QRLoginEventPayloadQRLoginExpiredOrRejected:
		x := QRLoginExpiredOrRejected{_tab: table}
		return &QRLoginEventPayloadT{Type: QRLoginEventPayloadQRLoginExpiredOrRejected, Value: x.UnPack()}
	}
	return nil
}
