// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RejectQRLoginResponseT struct {
	Ok bool `json:"ok"`
}

func (t *RejectQRLoginResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	RejectQRLoginResponseStart(builder)
	RejectQRLoginResponseAddOk(builder, t.Ok)
	return RejectQRLoginResponseEnd(builder)
}

func (rcv *RejectQRLoginResponse) UnPackTo(t *RejectQRLoginResponseT) {
	t.Ok = rcv.Ok()
}

func (rcv *RejectQRLoginResponse) UnPack() *RejectQRLoginResponseT {
	if rcv == nil {
		return nil
	}
	t := &RejectQRLoginResponseT{}
	rcv.UnPackTo(t)
	return t
}

type RejectQRLoginResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsRejectQRLoginResponse(buf []byte, offset flatbuffers.UOffsetT) *RejectQRLoginResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RejectQRLoginResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsRejectQRLoginResponse(buf []byte, offset flatbuffers.UOffsetT) *RejectQRLoginResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RejectQRLoginResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *RejectQRLoginResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RejectQRLoginResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RejectQRLoginResponse) Ok() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *RejectQRLoginResponse) MutateOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func RejectQRLoginResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RejectQRLoginResponseAddOk(builder *flatbuffers.Builder, ok bool) {
	builder.PrependBoolSlot(0, ok, false)
}
func RejectQRLoginResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
