// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RejectQRLoginRequestT struct {
	Token string `json:"token"`
}

func (t *RejectQRLoginRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	tokenOffset := builder.CreateString(t.Token)
	RejectQRLoginRequestStart(builder)
	RejectQRLoginRequestAddToken(builder, tokenOffset)
	return RejectQRLoginRequestEnd(builder)
}

func (rcv *RejectQRLoginRequest) UnPackTo(t *RejectQRLoginRequestT) {
	t.Token = string(rcv.Token())
}

func (rcv *RejectQRLoginRequest) UnPack() *RejectQRLoginRequestT {
	if rcv == nil {
		return nil
	}
	t := &RejectQRLoginRequestT{}
	rcv.UnPackTo(t)
	return t
}

type RejectQRLoginRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsRejectQRLoginRequest(buf []byte, offset flatbuffers.UOffsetT) *RejectQRLoginRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RejectQRLoginRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsRejectQRLoginRequest(buf []byte, offset flatbuffers.UOffsetT) *RejectQRLoginRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RejectQRLoginRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *RejectQRLoginRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RejectQRLoginRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RejectQRLoginRequest) Token() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RejectQRLoginRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RejectQRLoginRequestAddToken(builder *flatbuffers.Builder, token flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(token), 0)
}
func RejectQRLoginRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
