// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ResumeSessionResponseT struct {
	AuthKeyId uint64 `json:"auth_key_id"`
	UserId    int32  `json:"user_id"`
}

func (t *ResumeSessionResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	ResumeSessionResponseStart(builder)
	ResumeSessionResponseAddAuthKeyId(builder, t.AuthKeyId)
	ResumeSessionResponseAddUserId(builder, t.UserId)
	return ResumeSessionResponseEnd(builder)
}

func (rcv *ResumeSessionResponse) UnPackTo(t *ResumeSessionResponseT) {
	t.AuthKeyId = rcv.AuthKeyId()
	t.UserId = rcv.UserId()
}

func (rcv *ResumeSessionResponse) UnPack() *ResumeSessionResponseT {
	if rcv == nil {
		return nil
	}
	t := &ResumeSessionResponseT{}
	rcv.UnPackTo(t)
	return t
}

type ResumeSessionResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsResumeSessionResponse(buf []byte, offset flatbuffers.UOffsetT) *ResumeSessionResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ResumeSessionResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsResumeSessionResponse(buf []byte, offset flatbuffers.UOffsetT) *ResumeSessionResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ResumeSessionResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ResumeSessionResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ResumeSessionResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ResumeSessionResponse) AuthKeyId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ResumeSessionResponse) MutateAuthKeyId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *ResumeSessionResponse) UserId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ResumeSessionResponse) MutateUserId(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func ResumeSessionResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ResumeSessionResponseAddAuthKeyId(builder *flatbuffers.Builder, authKeyId uint64) {
	builder.PrependUint64Slot(0, authKeyId, 0)
}
func ResumeSessionResponseAddUserId(builder *flatbuffers.Builder, userId int32) {
	builder.PrependInt32Slot(1, userId, 0)
}
func ResumeSessionResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
