// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ResumeSessionRequestT struct {
	AuthKeyId    uint64 `json:"auth_key_id"`
	ResumeSecret string `json:"resume_secret"`
}

func (t *ResumeSessionRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	resumeSecretOffset := builder.CreateString(t.ResumeSecret)
	ResumeSessionRequestStart(builder)
	ResumeSessionRequestAddAuthKeyId(builder, t.AuthKeyId)
	ResumeSessionRequestAddResumeSecret(builder, resumeSecretOffset)
	return ResumeSessionRequestEnd(builder)
}

func (rcv *ResumeSessionRequest) UnPackTo(t *ResumeSessionRequestT) {
	t.AuthKeyId = rcv.AuthKeyId()
	t.ResumeSecret = string(rcv.ResumeSecret())
}

func (rcv *ResumeSessionRequest) UnPack() *ResumeSessionRequestT {
	if rcv == nil {
		return nil
	}
	t := &ResumeSessionRequestT{}
	rcv.UnPackTo(t)
	return t
}

type ResumeSessionRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsResumeSessionRequest(buf []byte, offset flatbuffers.UOffsetT) *ResumeSessionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ResumeSessionRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsResumeSessionRequest(buf []byte, offset flatbuffers.UOffsetT) *ResumeSessionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ResumeSessionRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ResumeSessionRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ResumeSessionRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ResumeSessionRequest) AuthKeyId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ResumeSessionRequest) MutateAuthKeyId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *ResumeSessionRequest) ResumeSecret() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ResumeSessionRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ResumeSessionRequestAddAuthKeyId(builder *flatbuffers.Builder, authKeyId uint64) {
	builder.PrependUint64Slot(0, authKeyId, 0)
}
func ResumeSessionRequestAddResumeSecret(builder *flatbuffers.Builder, resumeSecret flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(resumeSecret), 0)
}
func ResumeSessionRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
