// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ScanQRLoginResponseT struct {
	Ok               bool              `json:"ok"`
	FailReason       QRLoginFailReason `json:"fail_reason"`
	WaiterDeviceName string            `json:"waiter_device_name"`
	WaiterPlatform   Platform          `json:"waiter_platform"`
	WaiterOs         string            `json:"waiter_os"`
}

func (t *ScanQRLoginResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	waiterDeviceNameOffset := builder.CreateString(t.WaiterDeviceName)
	waiterOsOffset := builder.CreateString(t.WaiterOs)
	ScanQRLoginResponseStart(builder)
	ScanQRLoginResponseAddOk(builder, t.Ok)
	ScanQRLoginResponseAddFailReason(builder, t.FailReason)
	ScanQRLoginResponseAddWaiterDeviceName(builder, waiterDeviceNameOffset)
	ScanQRLoginResponseAddWaiterPlatform(builder, t.WaiterPlatform)
	ScanQRLoginResponseAddWaiterOs(builder, waiterOsOffset)
	return ScanQRLoginResponseEnd(builder)
}

func (rcv *ScanQRLoginResponse) UnPackTo(t *ScanQRLoginResponseT) {
	t.Ok = rcv.Ok()
	t.FailReason = rcv.FailReason()
	t.WaiterDeviceName = string(rcv.WaiterDeviceName())
	t.WaiterPlatform = rcv.WaiterPlatform()
	t.WaiterOs = string(rcv.WaiterOs())
}

func (rcv *ScanQRLoginResponse) UnPack() *ScanQRLoginResponseT {
	if rcv == nil {
		return nil
	}
	t := &ScanQRLoginResponseT{}
	rcv.UnPackTo(t)
	return t
}

type ScanQRLoginResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsScanQRLoginResponse(buf []byte, offset flatbuffers.UOffsetT) *ScanQRLoginResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ScanQRLoginResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsScanQRLoginResponse(buf []byte, offset flatbuffers.UOffsetT) *ScanQRLoginResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ScanQRLoginResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ScanQRLoginResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ScanQRLoginResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ScanQRLoginResponse) Ok() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ScanQRLoginResponse) MutateOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *ScanQRLoginResponse) FailReason() QRLoginFailReason {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return QRLoginFailReason(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ScanQRLoginResponse) MutateFailReason(n QRLoginFailReason) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *ScanQRLoginResponse) WaiterDeviceName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ScanQRLoginResponse) WaiterPlatform() Platform {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return Platform(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ScanQRLoginResponse) MutateWaiterPlatform(n Platform) bool {
	return rcv._tab.MutateInt8Slot(10, int8(n))
}

func (rcv *ScanQRLoginResponse) WaiterOs() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ScanQRLoginResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func ScanQRLoginResponseAddOk(builder *flatbuffers.Builder, ok bool) {
	builder.PrependBoolSlot(0, ok, false)
}
func ScanQRLoginResponseAddFailReason(builder *flatbuffers.Builder, failReason QRLoginFailReason) {
	builder.PrependInt8Slot(1, int8(failReason), 0)
}
func ScanQRLoginResponseAddWaiterDeviceName(builder *flatbuffers.Builder, waiterDeviceName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(waiterDeviceName), 0)
}
func ScanQRLoginResponseAddWaiterPlatform(builder *flatbuffers.Builder, waiterPlatform Platform) {
	builder.PrependInt8Slot(3, int8(waiterPlatform), 0)
}
func ScanQRLoginResponseAddWaiterOs(builder *flatbuffers.Builder, waiterOs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(waiterOs), 0)
}
func ScanQRLoginResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
