// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ScanQRLoginRequestT struct {
	Token string `json:"token"`
}

func (t *ScanQRLoginRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	tokenOffset := builder.CreateString(t.Token)
	ScanQRLoginRequestStart(builder)
	ScanQRLoginRequestAddToken(builder, tokenOffset)
	return ScanQRLoginRequestEnd(builder)
}

func (rcv *ScanQRLoginRequest) UnPackTo(t *ScanQRLoginRequestT) {
	t.Token = string(rcv.Token())
}

func (rcv *ScanQRLoginRequest) UnPack() *ScanQRLoginRequestT {
	if rcv == nil {
		return nil
	}
	t := &ScanQRLoginRequestT{}
	rcv.UnPackTo(t)
	return t
}

type ScanQRLoginRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsScanQRLoginRequest(buf []byte, offset flatbuffers.UOffsetT) *ScanQRLoginRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ScanQRLoginRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsScanQRLoginRequest(buf []byte, offset flatbuffers.UOffsetT) *ScanQRLoginRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ScanQRLoginRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ScanQRLoginRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ScanQRLoginRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ScanQRLoginRequest) Token() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ScanQRLoginRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ScanQRLoginRequestAddToken(builder *flatbuffers.Builder, token flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(token), 0)
}
func ScanQRLoginRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
