// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SessionInfoT struct {
	AuthKeyId      uint64   `json:"auth_key_id"`
	IsCurrent      bool     `json:"is_current"`
	Platform       Platform `json:"platform"`
	Os             string   `json:"os"`
	DeviceName     string   `json:"device_name"`
	IpAddress      string   `json:"ip_address"`
	CreatedAtMs    int64    `json:"created_at_ms"`
	LastActiveAtMs int64    `json:"last_active_at_ms"`
}

func (t *SessionInfoT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	osOffset := builder.CreateString(t.Os)
	deviceNameOffset := builder.CreateString(t.DeviceName)
	ipAddressOffset := builder.CreateString(t.IpAddress)
	SessionInfoStart(builder)
	SessionInfoAddAuthKeyId(builder, t.AuthKeyId)
	SessionInfoAddIsCurrent(builder, t.IsCurrent)
	SessionInfoAddPlatform(builder, t.Platform)
	SessionInfoAddOs(builder, osOffset)
	SessionInfoAddDeviceName(builder, deviceNameOffset)
	SessionInfoAddIpAddress(builder, ipAddressOffset)
	SessionInfoAddCreatedAtMs(builder, t.CreatedAtMs)
	SessionInfoAddLastActiveAtMs(builder, t.LastActiveAtMs)
	return SessionInfoEnd(builder)
}

func (rcv *SessionInfo) UnPackTo(t *SessionInfoT) {
	t.AuthKeyId = rcv.AuthKeyId()
	t.IsCurrent = rcv.IsCurrent()
	t.Platform = rcv.Platform()
	t.Os = string(rcv.Os())
	t.DeviceName = string(rcv.DeviceName())
	t.IpAddress = string(rcv.IpAddress())
	t.CreatedAtMs = rcv.CreatedAtMs()
	t.LastActiveAtMs = rcv.LastActiveAtMs()
}

func (rcv *SessionInfo) UnPack() *SessionInfoT {
	if rcv == nil {
		return nil
	}
	t := &SessionInfoT{}
	rcv.UnPackTo(t)
	return t
}

type SessionInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsSessionInfo(buf []byte, offset flatbuffers.UOffsetT) *SessionInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SessionInfo{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSessionInfo(buf []byte, offset flatbuffers.UOffsetT) *SessionInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SessionInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SessionInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SessionInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SessionInfo) AuthKeyId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SessionInfo) MutateAuthKeyId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *SessionInfo) IsCurrent() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SessionInfo) MutateIsCurrent(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *SessionInfo) Platform() Platform {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return Platform(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *SessionInfo) MutatePlatform(n Platform) bool {
	return rcv._tab.MutateInt8Slot(8, int8(n))
}

func (rcv *SessionInfo) Os() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SessionInfo) DeviceName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SessionInfo) IpAddress() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SessionInfo) CreatedAtMs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SessionInfo) MutateCreatedAtMs(n int64) bool {
	return rcv._tab.MutateInt64Slot(16, n)
}

func (rcv *SessionInfo) LastActiveAtMs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SessionInfo) MutateLastActiveAtMs(n int64) bool {
	return rcv._tab.MutateInt64Slot(18, n)
}

func SessionInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func SessionInfoAddAuthKeyId(builder *flatbuffers.Builder, authKeyId uint64) {
	builder.PrependUint64Slot(0, authKeyId, 0)
}
func SessionInfoAddIsCurrent(builder *flatbuffers.Builder, isCurrent bool) {
	builder.PrependBoolSlot(1, isCurrent, false)
}
func SessionInfoAddPlatform(builder *flatbuffers.Builder, platform Platform) {
	builder.PrependInt8Slot(2, int8(platform), 0)
}
func SessionInfoAddOs(builder *flatbuffers.Builder, os flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(os), 0)
}
func SessionInfoAddDeviceName(builder *flatbuffers.Builder, deviceName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(deviceName), 0)
}
func SessionInfoAddIpAddress(builder *flatbuffers.Builder, ipAddress flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(ipAddress), 0)
}
func SessionInfoAddCreatedAtMs(builder *flatbuffers.Builder, createdAtMs int64) {
	builder.PrependInt64Slot(6, createdAtMs, 0)
}
func SessionInfoAddLastActiveAtMs(builder *flatbuffers.Builder, lastActiveAtMs int64) {
	builder.PrependInt64Slot(7, lastActiveAtMs, 0)
}
func SessionInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
