// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TerminateSessionResponseT struct {
	Ok bool `json:"ok"`
}

func (t *TerminateSessionResponseT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	TerminateSessionResponseStart(builder)
	TerminateSessionResponseAddOk(builder, t.Ok)
	return TerminateSessionResponseEnd(builder)
}

func (rcv *TerminateSessionResponse) UnPackTo(t *TerminateSessionResponseT) {
	t.Ok = rcv.Ok()
}

func (rcv *TerminateSessionResponse) UnPack() *TerminateSessionResponseT {
	if rcv == nil {
		return nil
	}
	t := &TerminateSessionResponseT{}
	rcv.UnPackTo(t)
	return t
}

type TerminateSessionResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsTerminateSessionResponse(buf []byte, offset flatbuffers.UOffsetT) *TerminateSessionResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TerminateSessionResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTerminateSessionResponse(buf []byte, offset flatbuffers.UOffsetT) *TerminateSessionResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TerminateSessionResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TerminateSessionResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TerminateSessionResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TerminateSessionResponse) Ok() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TerminateSessionResponse) MutateOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func TerminateSessionResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TerminateSessionResponseAddOk(builder *flatbuffers.Builder, ok bool) {
	builder.PrependBoolSlot(0, ok, false)
}
func TerminateSessionResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
