// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TerminateSessionRequestT struct {
	Reason string `json:"reason"`
}

func (t *TerminateSessionRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	reasonOffset := builder.CreateString(t.Reason)
	TerminateSessionRequestStart(builder)
	TerminateSessionRequestAddReason(builder, reasonOffset)
	return TerminateSessionRequestEnd(builder)
}

func (rcv *TerminateSessionRequest) UnPackTo(t *TerminateSessionRequestT) {
	t.Reason = string(rcv.Reason())
}

func (rcv *TerminateSessionRequest) UnPack() *TerminateSessionRequestT {
	if rcv == nil {
		return nil
	}
	t := &TerminateSessionRequestT{}
	rcv.UnPackTo(t)
	return t
}

type TerminateSessionRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsTerminateSessionRequest(buf []byte, offset flatbuffers.UOffsetT) *TerminateSessionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TerminateSessionRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTerminateSessionRequest(buf []byte, offset flatbuffers.UOffsetT) *TerminateSessionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TerminateSessionRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TerminateSessionRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TerminateSessionRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TerminateSessionRequest) Reason() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func TerminateSessionRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TerminateSessionRequestAddReason(builder *flatbuffers.Builder, reason flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(reason), 0)
}
func TerminateSessionRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
