// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package authv1

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type WaitQRLoginResultRequestT struct {
	Token string `json:"token"`
}

func (t *WaitQRLoginResultRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	tokenOffset := builder.CreateString(t.Token)
	WaitQRLoginResultRequestStart(builder)
	WaitQRLoginResultRequestAddToken(builder, tokenOffset)
	return WaitQRLoginResultRequestEnd(builder)
}

func (rcv *WaitQRLoginResultRequest) UnPackTo(t *WaitQRLoginResultRequestT) {
	t.Token = string(rcv.Token())
}

func (rcv *WaitQRLoginResultRequest) UnPack() *WaitQRLoginResultRequestT {
	if rcv == nil {
		return nil
	}
	t := &WaitQRLoginResultRequestT{}
	rcv.UnPackTo(t)
	return t
}

type WaitQRLoginResultRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsWaitQRLoginResultRequest(buf []byte, offset flatbuffers.UOffsetT) *WaitQRLoginResultRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WaitQRLoginResultRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsWaitQRLoginResultRequest(buf []byte, offset flatbuffers.UOffsetT) *WaitQRLoginResultRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &WaitQRLoginResultRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *WaitQRLoginResultRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WaitQRLoginResultRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WaitQRLoginResultRequest) Token() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func WaitQRLoginResultRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func WaitQRLoginResultRequestAddToken(builder *flatbuffers.Builder, token flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(token), 0)
}
func WaitQRLoginResultRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
